services:
  app:
    build:
      context: ./
      target: base
      dockerfile: ./.docker/Dockerfile
    env_file:
      - .env
    volumes:
      - ./:/app
      - node_modules:/app/node_modules
    ports:
      - ${PORT}:${PORT}
    command: npm run serve

volumes:
  node_modules:
